---
dependencies: []

galaxy_info:
  role_name: f5ansible
  author: caphrim007
  description: Ansible role that allows use of the F5 Ansible Modules
  company: F5 Networks
  license: GPLv3
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - f5
    - networking
    - bigip
    - bigiq
